service:
 name: {{name}}
 type: {{type}}
 port: {{port}}
 targetPort: {{targetPort}}
 namespace: {{namespace}}
blog:
  name: {{name}}
  replicas: {{replicas}}
  image: {{image}}
  imagePullPolicy: {{imagePullPolicy}}
  containerPort: {{containerPort}}
  namespace: {{namespace}}
  maxUnavailable: {{maxUnavailable}}
  maxSurge: {{maxSurge}}
hpa:
 name: {{name}}
 namespace: {{namespace}}
 maxReplicas: {{maxReplicas}}
 minReplicas: {{minReplicas}}
 averageUtilization: {{averageUtilization}}
 averageValue: {{averageValue}}
