kind: HorizontalPodAutoscaler 
apiVersion: autoscaling/v2beta2
metadata: 
  name: {{ .Values.hpa.name }}
  namespace: {{ .Values.hpa.namespace }}
spec: 
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  scaleTargetRef: 
    apiVersion: apps/v1 
    kind: Deployment
    name: {{ .Values.hpa.name }} 
  metrics: 
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization      
        averageUtilization: {{ .Values.hpa.averageUtilization }}
  - type: Resource    
    resource:
      name: memory
      target:
        type: AverageValue           
        averageValue: {{ .Values.hpa.averageValue }}
